# Generated by Django 5.0.6 on 2024-07-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_desc_contact_decs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decs',
            new_name='desc',
        ),
    ]
